// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jGCbHcjfpjfhAqJxWaJyK1zCTQz4LsU',
    appId: '1:750597344397:web:8e2f007b370aaefc6026c4',
    messagingSenderId: '750597344397',
    projectId: 'campus-app-4c5fb',
    authDomain: 'campus-app-4c5fb.firebaseapp.com',
    storageBucket: 'campus-app-4c5fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXb_XWr-i-uqbsNpG8Sh_xKTjhYMVQkXI',
    appId: '1:750597344397:android:56b778c2688de2906026c4',
    messagingSenderId: '750597344397',
    projectId: 'campus-app-4c5fb',
    storageBucket: 'campus-app-4c5fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDa7HC5YL0nBtBkZpxqAcrPgTtvW6s4jU',
    appId: '1:750597344397:ios:f47d49b22a1f41316026c4',
    messagingSenderId: '750597344397',
    projectId: 'campus-app-4c5fb',
    storageBucket: 'campus-app-4c5fb.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDa7HC5YL0nBtBkZpxqAcrPgTtvW6s4jU',
    appId: '1:750597344397:ios:f47d49b22a1f41316026c4',
    messagingSenderId: '750597344397',
    projectId: 'campus-app-4c5fb',
    storageBucket: 'campus-app-4c5fb.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jGCbHcjfpjfhAqJxWaJyK1zCTQz4LsU',
    appId: '1:750597344397:web:6a158d92d0b7d4956026c4',
    messagingSenderId: '750597344397',
    projectId: 'campus-app-4c5fb',
    authDomain: 'campus-app-4c5fb.firebaseapp.com',
    storageBucket: 'campus-app-4c5fb.firebasestorage.app',
  );
}
